# H2 configuración
spring.datasource.url=jdbc:h2:mem:videoclub;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Mostrar SQL
spring.jpa.show-sql=true

# Que Hibernate cree las tablas
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create

# Que data.sql se ejecute **después** de que JPA cree las tablas
spring.sql.init.mode=always
spring.sql.init.platform=h2

# H2 consola
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
